### ISSUE TITLE
希望增加安装后清理安装包的功能

### ISSUE THREAD

**Issue by Qing-Novel** [Ium-Lab/Apk.1-Installer#5]
偶然间发现安装完安装包后data文件夹里的安装包文件不会被清除，一两个还好，多了就比较麻烦，希望能加个自动清理（录屏中的图标是做在主题里的，并没有修改软件的图标）

https://github.com/Ium-Lab/Apk.1-Installer/assets/136884931/ec71d7fa-9152-4d3d-9ce4-ca22aa4bb35a

**Comment by Ium-Lab** [comment]
最多只会存在一个，每次都会覆盖上一个，如果把安装器卸载了也会自动删除这个文件。自动删除需要增加监听，我试试效果哈
